name: Push-to-EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            whoami
            cd /opt/prasanth/portfolio
            sudo git branch
            sudo git checkout master
            sudo git pull
            npm --version
            npm install pm2 -g
            pm2 --version
            npm install
            npm run build
            pm2 start ecosystem.config.ts --env prod
            pm2 list
            echo "SUCCESS" 

